spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: toor
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: reports-api
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
springdoc:
  swagger-ui:
    path: swagger-ui.html
